# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\"\x16\n\x03req\x12\x0f\n\x07message\x18\x06 \x02(\t\"\x05\n\x03res2\x1c\n\x04Node\x12\x14\n\x04main\x12\x04.req\x1a\x04.res\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQ']._serialized_start=14
  _globals['_REQ']._serialized_end=36
  _globals['_RES']._serialized_start=38
  _globals['_RES']._serialized_end=43
  _globals['_NODE']._serialized_start=45
  _globals['_NODE']._serialized_end=73
# @@protoc_insertion_point(module_scope)
