# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_reduce.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10map_reduce.proto\"8\n\x0eMapDataRequest\x12\x13\n\x0binput_split\x18\x01 \x03(\x02\x12\x11\n\tcentroids\x18\x02 \x03(\x02\"+\n\x0fMapDataResponse\x12\x18\n\x05pairs\x18\x01 \x03(\x0b\x32\t.KeyValue\"%\n\x11ReduceDataRequest\x12\x10\n\x08reducers\x18\x01 \x01(\x05\"%\n\x12ReduceDataResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x11MapperDataRequest\x12\x11\n\tmapper_id\x18\x01 \x02(\x05\")\n\x12MapperDataResponse\x12\x13\n\x0b\x64\x61ta_points\x18\x01 \x03(\x02\"&\n\x10\x44\x61taPointRequest\x12\x12\n\ndata_point\x18\x01 \x02(\x02\"+\n\x11\x44\x61taPointResponse\x12\x16\n\x0e\x63\x65ntroid_index\x18\x01 \x02(\x05\"@\n\x10PartitionRequest\x12\x12\n\nreducer_id\x18\x01 \x02(\x05\x12\x18\n\x05pairs\x18\x02 \x03(\x0b\x32\t.KeyValue\"$\n\x11PartitionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x02(\x02\x12\r\n\x05value\x18\x02 \x03(\x02\x32\x83\x01\n\rMasterService\x12\x35\n\x0eSendMapperData\x12\x0f.MapDataRequest\x1a\x10.MapDataResponse\"\x00\x12;\n\x0eInvokeReducers\x12\x12.ReduceDataRequest\x1a\x13.ReduceDataResponse\"\x00\x32I\n\rMapperService\x12\x38\n\rSendDataPoint\x12\x11.DataPointRequest\x1a\x12.DataPointResponse\"\x00\x32J\n\x0eReducerService\x12\x38\n\rSendPartition\x12\x11.PartitionRequest\x1a\x12.PartitionResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_reduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPDATAREQUEST']._serialized_start=20
  _globals['_MAPDATAREQUEST']._serialized_end=76
  _globals['_MAPDATARESPONSE']._serialized_start=78
  _globals['_MAPDATARESPONSE']._serialized_end=121
  _globals['_REDUCEDATAREQUEST']._serialized_start=123
  _globals['_REDUCEDATAREQUEST']._serialized_end=160
  _globals['_REDUCEDATARESPONSE']._serialized_start=162
  _globals['_REDUCEDATARESPONSE']._serialized_end=199
  _globals['_MAPPERDATAREQUEST']._serialized_start=201
  _globals['_MAPPERDATAREQUEST']._serialized_end=239
  _globals['_MAPPERDATARESPONSE']._serialized_start=241
  _globals['_MAPPERDATARESPONSE']._serialized_end=282
  _globals['_DATAPOINTREQUEST']._serialized_start=284
  _globals['_DATAPOINTREQUEST']._serialized_end=322
  _globals['_DATAPOINTRESPONSE']._serialized_start=324
  _globals['_DATAPOINTRESPONSE']._serialized_end=367
  _globals['_PARTITIONREQUEST']._serialized_start=369
  _globals['_PARTITIONREQUEST']._serialized_end=433
  _globals['_PARTITIONRESPONSE']._serialized_start=435
  _globals['_PARTITIONRESPONSE']._serialized_end=471
  _globals['_KEYVALUE']._serialized_start=473
  _globals['_KEYVALUE']._serialized_end=511
  _globals['_MASTERSERVICE']._serialized_start=514
  _globals['_MASTERSERVICE']._serialized_end=645
  _globals['_MAPPERSERVICE']._serialized_start=647
  _globals['_MAPPERSERVICE']._serialized_end=720
  _globals['_REDUCERSERVICE']._serialized_start=722
  _globals['_REDUCERSERVICE']._serialized_end=796
# @@protoc_insertion_point(module_scope)
