# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\"2\n\nitemBought\x12\x12\n\nproduct_id\x18\x01 \x02(\x05\x12\x10\n\x08quantity\x18\x02 \x02(\x05\"\xc9\x01\n\tsoldItems\x12\n\n\x02ip\x18\n \x02(\t\x12\x14\n\x0cproduct_name\x18\x0b \x02(\t\x12%\n\x08\x63\x61tegory\x18\x03 \x02(\x0e\x32\x13.soldItems.Category\x12\x10\n\x08quantity\x18\x04 \x02(\x05\x12\x13\n\x0b\x64\x65scription\x18\x0c \x02(\t\x12\x16\n\x0eprice_per_unit\x18\x07 \x02(\x01\"4\n\x08\x43\x61tegory\x12\x0f\n\x0b\x45LECTRONICS\x10\x01\x12\x0b\n\x07\x46\x41SHION\x10\x02\x12\n\n\x06OTHERS\x10\x03\"Q\n\x11\x64isplaySellerItem\x12\x18\n\x04item\x18\x05 \x02(\x0b\x32\n.soldItems\x12\x12\n\nproduct_id\x18\x01 \x02(\x05\x12\x0e\n\x06rating\x18\x03 \x02(\x01\"\x07\n\x05\x45mpty23\n\x05\x42uyer\x12*\n\nupdateItem\x12\x12.displaySellerItem\x1a\x06.Empty\"\x00\x32\x65\n\x06Seller\x12/\n\x0fItemBoughtNotif\x12\x12.displaySellerItem\x1a\x06.Empty\"\x00\x12*\n\nupdateItem\x12\x12.displaySellerItem\x1a\x06.Empty\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEMBOUGHT']._serialized_start=16
  _globals['_ITEMBOUGHT']._serialized_end=66
  _globals['_SOLDITEMS']._serialized_start=69
  _globals['_SOLDITEMS']._serialized_end=270
  _globals['_SOLDITEMS_CATEGORY']._serialized_start=218
  _globals['_SOLDITEMS_CATEGORY']._serialized_end=270
  _globals['_DISPLAYSELLERITEM']._serialized_start=272
  _globals['_DISPLAYSELLERITEM']._serialized_end=353
  _globals['_EMPTY']._serialized_start=355
  _globals['_EMPTY']._serialized_end=362
  _globals['_BUYER']._serialized_start=364
  _globals['_BUYER']._serialized_end=415
  _globals['_SELLER']._serialized_start=417
  _globals['_SELLER']._serialized_end=518
# @@protoc_insertion_point(module_scope)
