# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import client_pb2 as client__pb2


class BuyerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.updateItem = channel.unary_unary(
                '/Buyer/updateItem',
                request_serializer=client__pb2.displaySellerItem.SerializeToString,
                response_deserializer=client__pb2.Empty.FromString,
                )


class BuyerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def updateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'updateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.updateItem,
                    request_deserializer=client__pb2.displaySellerItem.FromString,
                    response_serializer=client__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Buyer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Buyer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def updateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Buyer/updateItem',
            client__pb2.displaySellerItem.SerializeToString,
            client__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SellerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ItemBoughtNotif = channel.unary_unary(
                '/Seller/ItemBoughtNotif',
                request_serializer=client__pb2.displaySellerItem.SerializeToString,
                response_deserializer=client__pb2.Empty.FromString,
                )
        self.updateItem = channel.unary_unary(
                '/Seller/updateItem',
                request_serializer=client__pb2.displaySellerItem.SerializeToString,
                response_deserializer=client__pb2.Empty.FromString,
                )


class SellerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ItemBoughtNotif(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SellerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ItemBoughtNotif': grpc.unary_unary_rpc_method_handler(
                    servicer.ItemBoughtNotif,
                    request_deserializer=client__pb2.displaySellerItem.FromString,
                    response_serializer=client__pb2.Empty.SerializeToString,
            ),
            'updateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.updateItem,
                    request_deserializer=client__pb2.displaySellerItem.FromString,
                    response_serializer=client__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Seller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Seller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ItemBoughtNotif(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Seller/ItemBoughtNotif',
            client__pb2.displaySellerItem.SerializeToString,
            client__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Seller/updateItem',
            client__pb2.displaySellerItem.SerializeToString,
            client__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
